replicaCount: 3
image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "stable"
podAnnotations:
  checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
env:
  name: dev
labels:
  app: task-app-dev
deployment:
  name: deployment-dev
service:
  name: service-dev
configmap:
  name: configmap-dev
secret:
  name: secret-dev
ingress:
  name: ingress-dev
replicaset:
  name: replicaset-dev
volumeMounts:
  name: config-volume
  mountPath: /app/config.json
  subPath: config.json