replicaCount: 5
image:
  repository: busybox
  pullPolicy: IfNotPresent
  tag: "stable"
podAnnotations:
  checksum/config: '{{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}'
env:
  name: prd
labels:
  app: task-app-prd
deployment:
  name: deployment-prd
service:
  name: service-prd
configmap:
  name: configmap-prd
secret:
  name: secret-prd
ingress:
  name: ingress-prd
replicaset:
  name: replicaset-prd
volumeMounts:
  name: config-volume
  mountPath: /app/config.json
  subPath: config.json